minecraft:
  version: 1.21.1
  source: mojang
fabric:
  version: 0.17.3
  source: fabric
mods:
- name: adorabuild-structures
  version: 2.8.0
  source: modrinth
  environment: both
- name: aether
  version: 1.21.1-1.5.11-fabric
  source: modrinth
  environment: both
- name: AmbientSounds
  version: 6.1.4
  source: modrinth
  slug: ambientsounds
  environment: client
- name: amendments
  version: fabric_1.21-2.0.8
  source: modrinth
  environment: both
- name: animatica
  version: 0.6.1+1.21
  source: modrinth
  environment: client
- name: appleskin
  version: 3.0.6+mc1.21
  source: modrinth
  environment: both
- name: architectury-api
  version: 13.0.8+fabric
  source: modrinth
  environment: both
- name: artifacts
  version: 12.0.6
  source: modrinth
  environment: both
- name: autohud
  version: 8.7+1.21.1-fabric
  source: modrinth
  environment: client
- name: better-third-person
  version: 1.9.0
  source: modrinth
  environment: client
- name: c2me-fabric
  version: 0.3.0+alpha.0.362+1.21.1
  source: modrinth
  environment: both
- name: capes
  version: 1.5.4+1.21
  source: modrinth
  environment: client
- name: cardinal-components-api
  version: 6.1.1
  source: modrinth
  environment: both
- name: cit-resewn
  version: 1.2.1+1.21
  source: modrinth
  environment: client
- name: cloth-config
  version: 15.0.140+fabric
  source: modrinth
  environment: both
- name: collective
  version: 1.21.1-8.13-fabric+forge+neo
  source: modrinth
  environment: both
- name: comforts
  version: 9.0.4+1.21.1
  source: modrinth
  environment: both
- name: continuity
  version: 3.0.0-beta.5+1.21
  source: modrinth
  environment: client
- name: Corgilib
  version: 1.21.1-5.0.0.7-Fabric
  source: modrinth
  environment: both
- name: coroutil
  version: 1.21.1-1.3.8
  source: modrinth
  environment: both
- name: CreativeCore
  version: 2.12.23
  source: modrinth
  environment: both
- name: cristel-lib
  version: fabric-1.21.1-3.0.2
  source: modrinth
  environment: both
- name: custom-fog
  version: 2.2.1-1.21
  source: modrinth
  environment: both
- name: DistantHorizons
  version: 2.3.6-b-1.21.1
  source: modrinth
  environment: both
- name: when-dungeons-arise
  version: 2.1.60
  source: modrinth
  environment: server
- name: when-dungeons-arise-seven-seas
  version: 1.0.3
  source: modrinth
  environment: server
- name: dynamic-fps
  version: 3.7.2
  source: modrinth
  environment: client
- name: ebe
  version: 0.10.2+1.21
  source: modrinth
  environment: client
- name: Enhanced-Celestials
  version: 6.0.2.5-fabric
  source: modrinth
  environment: both
- name: entity-model-features
  version: 2.2.6
  source: modrinth
  environment: client
- name: entitytexturefeatures
  version: 6.2.5
  source: modrinth
  environment: client
- name: entityculling
  version: 1.7.0
  source: modrinth
  environment: client
- name: evenmoreinstruments
  version: fabric-1.21+1.21.1-6.1.4
  source: modrinth
  environment: both
- name: fabric-api
  version: 0.115.0+1.21.1
  source: modrinth
  environment: both
- name: fabric-language-kotlin
  version: 1.12.2+kotlin.2.0.20
  source: modrinth
  environment: both
- name: nuit
  version: mc1.21-0.7.4
  source: modrinth
  environment: client
- name: fabrishot
  version: 1.14.1
  source: modrinth
  environment: client
- name: farmers-delight-refabricated
  version: 1.21.1-3.2.2
  source: modrinth
  environment: both
- name: ferrite-core
  version: 7.0.2-hotfix-fabric
  source: modrinth
  environment: both
- name: flow
  version: 2.2.0+1.21
  source: modrinth
  environment: client
- name: framework
  project_id: 549225
  version: 0.9.4
  source: curseforge
- name: friends-and-foes
  version: fabric-4.0.15+mc1.21.1
  source: modrinth
  environment: both
- name: nuit-interop
  version: mc1.21-1.4.0
  source: modrinth
  environment: client
- name: geckolib
  version: 4.7.3
  source: modrinth
  environment: both
- name: genshin-instruments
  version: fabric-1.21+1.21.1-5.0.1
  source: modrinth
  environment: both
- name: Geophilic
  version: '3.2'
  source: modrinth
  environment: both
- name: GlitchCore
  version: 2.1.0.0
  source: modrinth
  environment: both
- name: ImmediatelyFast
  version: 1.6.7+1.21.1-fabric
  source: modrinth
  environment: client
- name: immersive-aircraft
  version: 1.1.6+1.21.1
  source: modrinth
  environment: both
- name: ImmersiveThunder
  version: 1.21.1+1.2.2
  source: modrinth
  environment: client
- name: indium
  version: 1.0.35+mc1.21
  source: modrinth
  environment: client
- name: iris
  version: 1.8.8+1.21.1-fabric
  source: modrinth
  environment: client
- name: item-scroller
  version: 0.24.50
  source: modrinth
  environment: client
- name: krypton
  version: 0.2.8
  source: modrinth
  environment: both
- name: lazy-language-loader
  version: 0.3.7
  source: modrinth
  environment: client
- name: lithium
  version: mc1.21.1-0.15.0-fabric
  source: modrinth
  environment: both
- name: malilib
  version: 0.21.0
  source: modrinth
  environment: client
- name: macaws-doors
  version: 1.1.1
  source: modrinth
  environment: both
- name: macaws-trapdoors
  version: 1.1.4
  source: modrinth
  environment: both
- name: mes-moogs-end-structures
  version: 1.4.6-1.21
  source: modrinth
  environment: server
- name: midnightcontrols
  version: 1.9.7+1.21
  source: modrinth
  environment: client
- name: midnightlib
  version: 1.7.5+1.21.1-fabric
  source: modrinth
  environment: both
- name: mmv-moogs-missing-villages
  version: 2.0.0
  source: modrinth
  environment: server
- name: mns-moogs-nether-structures
  version: 2.0.0
  source: modrinth
  environment: server
- name: modernfix
  version: 5.19.3+mc1.21.1
  source: modrinth
  environment: both
- name: modmenu
  version: 11.0.2
  source: modrinth
  environment: client
- name: moonlight
  version: 1.21-2.26.0-fabric
  source: modrinth
  environment: both
- name: moreculling
  version: 0.27.1
  source: modrinth
  environment: client
- name: mouse-tweaks
  version: 1.21-2.26-fabric
  source: modrinth
  environment: client
- name: MRU
  version: 1.0.19+LTS+1.21.1-fabric
  source: modrinth
  environment: both
- name: mss-moogs-soaring-structures
  version: 2.0.0
  source: modrinth
  environment: server
- name: moogs-voyager-structures
  version: 5.0.1
  source: modrinth
  environment: server
- name: no-telemetry
  version: 1.8.0
  source: modrinth
  environment: client
- name: not-enough-animations
  version: 1.9.1
  source: modrinth
  environment: client
- name: nyfs-spiders
  version: 2.3.2
  source: modrinth
  environment: both
- name: ObsidianUI
  version: 0.2.9+mc1.21.1-fabric
  source: modrinth
  environment: client
- name: optigui
  version: 2.3.0-beta.4+1.21
  source: modrinth
  environment: client
- name: OrthoCamera
  version: 0.1.8+1.21
  source: modrinth
  environment: client
- name: owo-lib
  version: 0.12.15.4+1.21
  source: modrinth
  environment: both
- name: physicsmod
  version: 3.0.23
  source: modrinth
  environment: client
- name: placeholder-api
  version: 2.4.1+1.21
  source: modrinth
  environment: both
- name: polytone
  version: 1.21-3.5.10
  source: modrinth
  environment: client
- name: preview_OptiFine
  version: 1.21_HD_U_J1_pre9
  source: custom
  download_url: https://optifine.net/downloadx?f=preview_OptiFine_1.21_HD_U_J1_pre9.jar&x=8e5b3e3c
- name: puzzle
  version: 2.0.1.1-fabric
  source: modrinth
  environment: client
- name: reeses-sodium-options
  version: mc1.21.4-1.8.3+fabric
  source: modrinth
  environment: client
- name: replaymod
  version: 1.21-2.6.23
  source: modrinth
  environment: client
- name: ryoamiclights
  version: 0.2.11+mc1.21.1-fabric
  source: modrinth
  environment: client
- name: serene-seasons
  version: 10.1.0.1
  source: modrinth
  environment: both
- name: small-ships
  version: 2.0.0-b2.1
  source: modrinth
  environment: both
- name: sodium-extra
  version: mc1.21.1-0.6.0+fabric
  source: modrinth
  environment: client
- name: sodium
  version: mc1.21.1-0.6.13-fabric
  source: modrinth
  environment: client
- name: sound-physics-remastered
  version: fabric-1.21.1-1.5.1
  source: modrinth
  environment: both
- name: sound
  version: 2.4.15+lts+1.21.1-fabric
  source: modrinth
  environment: client
- name: spiders-produce-webs
  version: 1.21.1-3.6-fabric+forge+neo
  source: modrinth
  environment: server
- name: supplementaries
  version: fabric_1.21-3.4.20
  source: modrinth
  environment: both
- name: tectonic
  version: 2.4.1a
  source: modrinth
  environment: both
- name: TerraBlender
  version: 4.1.0.8
  source: modrinth
  environment: both
- name: tree-harvester
  version: 1.21.1-9.1-fabric+forge+neo
  source: modrinth
  environment: server
- name: trinkets
  version: 3.10.0
  source: modrinth
  environment: both
- name: villages-and-pillages
  version: fabric-mc1.21.1-1.0.3
  source: modrinth
  environment: server
- name: wiretap
  version: 1.3.0+1.21.1.fabric
  source: modrinth
  environment: server
- name: fwaystones
  version: 3.3.4+mc1.21.1
  source: modrinth
  environment: both
- name: yungs-api
  version: 1.21.1-Fabric-5.1.6
  source: modrinth
  environment: both
- name: yungs-better-dungeons
  version: 1.21.1-Fabric-5.1.4
  source: modrinth
  environment: server
- name: yungs-better-nether-fortresses
  source: modrinth
  version: 1.21.1-Fabric-3.1.5
  environment: server
- name: yungs-better-caves
  source: modrinth
  version: 1.21.1-Fabric-3.1.4
  environment: server
- name: yungs-better-desert-temples
  source: modrinth
  version: 1.21.1-Fabric-4.1.5
  environment: server
- name: yungs-better-witch-huts
  source: modrinth
  version: 1.21.1-Fabric-4.1.1
  environment: server
- name: yungs-better-strongholds
  source: modrinth
  version: 1.21.1-Fabric-5.1.3
  environment: server
- name: yungs-better-end-island
  source: modrinth
  version: 1.21.1-Fabric-3.1.2
  environment: server
- name: yungs-better-jungle-temples
  source: modrinth
  version: 1.21.1-Fabric-3.1.2
  environment: server
- name: yungs-better-mineshafts
  source: modrinth
  version: 1.21.1-Fabric-5.1.1
  environment: server
- name: yungs-better-ocean-monuments
  source: modrinth
  version: 1.21.1-Fabric-4.1.2
  environment: server
- name: zombie-awareness
  version: 1.21.0-1.13.2
  source: modrinth
  environment: both
