version: '3.9'

services:
  minecraft:
    build: ./
    entrypoint: /home/minecraft/server/entrypoint.sh
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565
    volumes:
      - type: bind
        source: ./world/overworld
        target: /home/minecraft/server/world
      - type: bind
        source: ./world/nether
        target: /home/minecraft/server/world_nether
      - type: bind
        source: ./world/end
        target: /home/minecraft/server/world_the_end
      
